authors = ["mantyant <mantyant@gmail.com>"]
name = "InterfaceMechanics"
uuid = "d2649932-d9e0-11e8-27ac-0193def238a7"
version = "0.1.0"

[deps]

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
